version: '3.9'

services:
  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome
    volumes:
      - /docker/esphome/config:/config  # Configuraciones de ESPHome
      - /etc/localtime:/etc/localtime:ro  # Sincronizar zona horaria
    restart: unless-stopped
    environment:
      - USERNAME=usuario  # Credenciales de acceso
      - PASSWORD=Password

  # Servicio de videovigilancia NVR
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:0.16.0-beta2
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    shm_size: "512mb"  # Memoria compartida para procesamiento de video
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/frigate/config.yml:/config/config.yml  # Archivo de configuración
      - /docker/frigate_db:/media/frigate  # Almacenamiento de grabaciones
      - type: tmpfs  # Cache en memoria para reducir escritura en disco
        target: /tmp/cache
        tmpfs:
          size: 500000000  # 500MB de cache temporal
    ports:
      - "8972:8971"  # Puerto de la API
      - "5000:5000"  # Interfaz web
      - "8554:8554"  # RTSP feeds
      - "8555:8555/tcp" # WebRTC sobre TCP
      - "8555:8555/udp" # WebRTC sobre UDP
      - "1984:1984"  # go2rtc
    environment: 
      LIBVA_DRIVER_NAME: i965  # Aceleración por hardware para Intel

  # Sistema central de domótica

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /docker/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host


  # Broker MQTT para comunicación IoT
  mqtt:
    container_name: mosquitto1
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    ports:
      - "1883:1883"  # Puerto MQTT estándar
      - "9001:9001"  # Websocket para MQTT
    volumes:
      - /docker/mosquitto/config:/mqtt/config  # Configuración Mosquitto
      - /docker/mosquitto/log:/mqtt/log  # Registros del servicio
      - /docker/mosquitto/data:/mqtt/data  # Datos persistentes
