version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /docker/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /docker/mosquitto/config:/mqtt/config
      - /docker/mosquitto/log:/mqtt/log
      - /docker/mosquitto/data/:/mqtt/data
    restart: unless-stopped
    networks:
      iot:
        ipv4_address: 172.18.0.2

  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/frigate/config.yml:/config/config.yml
      - /media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5001:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment: 
      PLUS_API_KEY:
        c08bf441-650a-4afb-a9a0-71e9d66a766a:71c77e62cdb0576a028f5bdf76d83bfcc0fa7665
    networks:
      iot:
        ipv4_address: 172.18.0.3    

networks:
  iot:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
